### ISSUE TITLE
Pause -> unpause, during npc convo = player can move during convo now

### ISSUE THREAD

**Issue by jurcaua** [FinnbarrOC/EspionAge#187]
Harder to handle this nicely, having a DialogueManager of some sort so we always know the current state of dialogue, like "playerIsConversing" or something. Or maybe @chadleytan knows a better way?

Either way this is a rare thing the player will probably not do, so we don't have to prioritize this.

**Comment by chadleytan** [comment]
Another way would be just saving the previous state of the player can move when pausing and then just setting it back to that state after un-pausing but I definitely do agree that a DialogueManager would be better
