### ISSUE TITLE
Add wait time + rotation to each enemy patrol waypoint

### ISSUE THREAD

**Issue by jurcaua** [FinnbarrOC/EspionAge#215]
https://docs.unity3d.com/Manual/nav-CouplingAnimationAndNavigation.html

**Comment by fnnbrr** [comment]
Should also add a goal rotation to each waypoint, so that waypoints can be used to rotate an AI in place.

Would work best if this is combined with a refactor of AI movement so that the agents rotate, then move, then rotate to look more natural/be more predictable.
