### ISSUE TITLE
Mission Manager

### ISSUE THREAD

**Issue by fnnbrr** [FinnbarrOC/EspionAge#24]
General Interactions:
* Managing all available missions.
* Triggers the start and end of missions, working with other managers
  * Mission Start: (probably) Dialogue Manager OR Progression Manager -> Mission Manager
  * Mission End: Mission Manager -> (probably) Progression Manager
* Lays out the logic for mission-specific interactions.
  * Ex: waiting for user to interact with three things in level 1 in the kitchen, then triggering the spawning of enemies according the the order of items collected.

**Comment by jurcaua** [comment]
#32
