### ISSUE TITLE
Yoga residents do not turn back around after interaction

### ISSUE THREAD

**Issue by jurcaua** [FinnbarrOC/EspionAge#302]
![image](https://user-images.githubusercontent.com/11907795/77287274-8f715c80-6cab-11ea-9539-602d52ac99d1.png)

is this a bug, or intended behaviour?

**Comment by masonachu** [comment]
It would be really funny if one NPC does stop because Birdie says something
mean to them and they give up working out LOL

**Comment by chadleytan** [comment]
Ok definitely not intended functionality LOL.
Right now any NPC you talk to would always face towards the player. I could look into making a way to make this optional if wanted. Let me know!!!

**Comment by jurcaua** [comment]
Optional would be good maybe! This isn't a big deal though, just some later polish if we have time!

@masonachu we'll have to look into supporting like post-talk actions and all that, which would take some time, so maybe for now we can table that?
