### ISSUE TITLE
Make hedge maze area it's own restricted camera zone

### ISSUE THREAD

**Issue by jurcaua** [FinnbarrOC/EspionAge#350]
Should we also change the camera angle @FinnbarrOC ?
Maybe something that's actually facing forward towards the nurses room instead? Maybe the same camera distance is okay though... if anything, a smudge closer.

**Comment by fnnbrr** [comment]
Yeah I think that camera angle would make sense; it lets the player know that the correct way is forward through the maze & down the hallway.

For camera distance I'd be fine with closer, though it would be nice if the angle & distance still let the player see when Brutus gets alerted in his office and rushes to find them!

**Comment by jurcaua** [comment]
I think a UI element pointing to Brutus at all times would be nice, when he's off screen. Like on the edge of the screen, maybe with a cartoon picture of his face + an arrow? If you know what kind of thing I'm referring to? LOL

But yea definitely as a way to constantly tell the player where to go, if the camera angle was pointing in the right direction.

Also something to think about is the hallway portion, which is mostly a slow walk towards the final room. Maybe the slow down pace towards the final moments of the game is good... but maybe we would wana change that up to.

**Comment by jurcaua** [comment]
fixed in my latest pr
