### ISSUE TITLE
Awakeness meter doesn't show in hedge maze

### ISSUE THREAD

**Issue by fnnbrr** [FinnbarrOC/EspionAge#354]
I'm guessing the OutdoorZone will have to be marked as a restricted zone somewhere for this to work.

**Comment by jurcaua** [comment]
Yea, we can look into making it a dedicated CameraZone, with it's own camera like we mentioned before, and zone name, and mark it as restricted.

**Comment by jurcaua** [comment]
fixed in latest pr
