### ISSUE TITLE
Lock character movement on zone transition/camera rotation

### ISSUE THREAD

**Issue by fnnbrr** [FinnbarrOC/EspionAge#42]
When moving between safe & restricted zones, the directions of movement for each key become rotated to match the camera orientation.

This leads to janky behavior if the player is holding down any movement keys.

Easy fix would be to ignore player input for a second and automatically move the character forward into the new zone.

**Comment by jurcaua** [comment]
Events are set up for the camera blending, so it'll be a quick fix! Good call! 😁
